### ISSUE TITLE
css !important

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-a11y-checker#15]
almost all of the css is !important

My css is only slightly better than my javsscript but my gut feeling is that this is wrong. It might be a legacy thing when the css classes were not prefixed sally- and the !important was to prevent clashes with a site template.

**Comment by chmst** [comment]
You are right, this is not scss at all. 
It needs a complete review.

**Comment by brianteeman** [comment]
i know its not scss ;)
i just wanted to know if the !important was needed or not

**Comment by brianteeman** [comment]
I will **try** and write scss from scratch tomorrow

**Comment by chmst** [comment]
The !important could be needed in some cases - but if it is needed, then w see it in a live installation. 
@drmenzelit and I can help
