### ISSUE TITLE
How to setup dev environment

### ISSUE THREAD

**Issue by carcam** [joomla-projects/joomla-a11y-checker#16]
I'm starting to play around with Joomla a11y checker and I want to be sure about the best way to setup my dev environment. Also maybe I could help with some routines to set it up for others.

Benjamin npm work is great and provides the dist files out of the box but after that, how do I plug them into Joomla? I guess the final goal is to develop this as a plugin. Should I start that plugin code so that it's easier for us to integrate and test?

How do you currently test your work? Do you just link to the files in the template?

Thank you very much in advance!!

cc @brianteeman @bembelimen

**Comment by brianteeman** [comment]
You can not test it with Joomla just yet. There is a complete set of html pages you can use for tests at this time. I have **not** done any Joomla work with the script yet. Thats for the weekend. For now the priority is getting the script itself into perfect shape.

**Comment by carcam** [comment]
@brianteeman Thanks for your reply!! I will then use the html pages for testing.

Thanks!!

**Comment by Fedik** [comment]
The examples in the repository use `src/` code.

For use it in Joomla (or in another site) you have to include `dist/ `files.

```html
<link rel="stylesheet" href="dist/css/joomla-a11y-checker.css" />
<script src="dist/js/joomla-a11y-checker.umd.js" defer></script>
<script src="dist/js/lang/en.js" defer></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
     // Set translations
     Sa11y.Lang.addI18n(Sa11yLangEn.strings);

     // Instantiate
     const checker = new Sa11y.Sa11y(Sa11yLangEn.options);
  });
</script>
```

And comment this lines for now:
https://github.com/joomla-projects/joomla-a11y-checker/blob/4edc49f20af31ea6cc4a4cbb83c1e465d748ca9a/dist/js/joomla-a11y-checker.umd.js#L33-L39

Because we do not have translation in Joomla currently.

**Comment by Fedik** [comment]
Or wait when @brianteeman will prepare something :)

**Comment by brianteeman** [comment]
I plan to work on the joomla plugin over the weekend. But there are plenty of other issues to work on

**Comment by carcam** [comment]
Thanks @Fedik !!!
