### ISSUE TITLE
JavaScript testing

### ISSUE THREAD

**Issue by carcam** [joomla-projects/joomla-a11y-checker#19]
I'm far from being an expert in JavaScript or testing, but I feel this project will need some automated tests with mocha or similar. Do we (in Joomla) have any experience with that or a toolbox we can explore to add to this project?

**Comment by Fedik** [comment]
I found this https://docs.joomla.org/Running_JavaScript_Tests_for_the_Joomla_CMS
But I have no idea how actual it is :)

**Comment by dgrammatiko** [comment]
@Fedik that is broken but you can bring the tests from https://github.com/joomla-projects/custom-elements/blob/master/karma.conf.js
