### ISSUE TITLE
Language strings (line 112)

### ISSUE THREAD

**Issue by chmst** [joomla-projects/joomla-a11y-checker#25]
'Image is being used as a link with surrounding text, although the alt attribute should be marked as decorative or null.',

I don't understand this as non-native speaker. 
does it mean "The alt attribute should be marked as decorative or null because Image is being used as a link with surrounding text?

**Comment by Fedik** [comment]
It comes from this test: https://github.com/joomla-projects/joomla-a11y-checker/blob/1174e2029cad9533c048ec562ea5dc179e4dad4d/src/js/sa11y.js#L1711-L1717

It is for image that does not have `alt` and is wrapped with link, that contain text.
No idea what it means from a11y point of view :wink:

**Comment by chmst** [comment]
ahh - it is the word "although" - bad english - german translation in deepl ;)

**Comment by brianteeman** [comment]
It is easier to check the text on the examples

**Comment by chmst** [comment]
I understand it, of course. But think that user's don't - it is a challenge for translators.

**Comment by Fedik** [comment]
> although the alt attribute should be marked as decorative or null

Maybe more sense would be to say: `... should be marked as decorative or set empty`
I not sure what means "decorative"

**Comment by brianteeman** [comment]
Decorative is the term used in the ui

![image](https://user-images.githubusercontent.com/1296369/143221114-b51de4fc-325c-489d-bd04-bb502a70ca07.png)

**Comment by brianteeman** [comment]
but I agree that null is wrong and should be empty. I will review and update.
