### ISSUE TITLE
Warning for underlined text?

### ISSUE THREAD

**Issue by chmst** [joomla-projects/joomla-a11y-checker#27]
Not an issue but a question.

Is there a warning if text is underlined for highlighting. It is nor relevant for assistive technologies but for sighted users, as they expect that underlined text is a link

**Comment by brianteeman** [comment]
No  but it would be a good addition to highlight

**Comment by brianteeman** [comment]
and it would be very easy to add it here

https://github.com/joomla-projects/joomla-a11y-checker/blob/90c87ad8c93fc000349ddc8e351b35719d187c66/src/js/sa11y.js#L2179-L2187

**Comment by brianteeman** [comment]
Actually I'm not sure if any test we could write would be that effective.  checking for the tag `<u>` would cover some usecases but we couldnt really have a test if there was a class with a style `text-decoration: underline` unless it was an inline style. Maybe it all depends on how tinymce handles text pasted from word that is underlined?

**Comment by brianteeman** [comment]
Is this what you are looking for @chmst 

![image](https://user-images.githubusercontent.com/1296369/154801023-f3dd8291-e5a1-4284-b5d4-5bbef1615703.png)

**Comment by brianteeman** [comment]
please check #69
