### ISSUE TITLE
sa11y-panel-alert

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-a11y-checker#30]
As far as I can tell this div is created but can never be used.

If someone can check and confirm I can remove it

**Comment by Fedik** [comment]
It is used somehow https://github.com/joomla-projects/joomla-a11y-checker/blob/1174e2029cad9533c048ec562ea5dc179e4dad4d/src/js/sa11y.js#L1152

**Comment by brianteeman** [comment]
I saw that and I can see the div being created. I just can't see how it can ever be populated

**Comment by Fedik** [comment]
It something with navigation `skipToIssueToggle`, there 2 triggers: `Alt + Period` keyup (no idea even what is `Period` key) and some button `#sa11y-cycle-toggle`
https://github.com/joomla-projects/joomla-a11y-checker/blob/1174e2029cad9533c048ec562ea5dc179e4dad4d/src/js/sa11y.js#L1133-L1146

Well, I also do not really find how to trigger that :smile:

**Comment by brianteeman** [comment]
This is the skip link (alt .)

![image](https://user-images.githubusercontent.com/1296369/142854292-ccbce499-cc99-40b9-a634-fbcc7a62081c.png)

It is rendered in sa11y-panel-content not sa11y-panel-alert

![image](https://user-images.githubusercontent.com/1296369/142854466-e80bfb6a-6c21-41d3-89d7-1b7404700420.png)

**Comment by Fedik** [comment]
> It is rendered in sa11y-panel-content not sa11y-panel-alert

Not in panel-alert, but it toggle it somehow here:
https://github.com/joomla-projects/joomla-a11y-checker/blob/1174e2029cad9533c048ec562ea5dc179e4dad4d/src/js/sa11y.js#L1211-L1219

**Comment by brianteeman** [comment]
Found it.

When you navigate through the errors using the skip shortcut and the error is not visible eg inside a collapsed accordion slide then the message is displayed in the alert area.
