### ISSUE TITLE
Fails to start on load

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-a11y-checker#37]
Two issues possibly related

On page load the button should appear, the page is scanned, (with an animation on the button), and then the count of errors appears.

I realised today that this is not reliably happening. The button always appears but the animation and count do not appear

uncommenting lines 393-404 made an improvement but still not 100% 

@fedik You commented those lines https://github.com/joomla-projects/joomla-a11y-checker/commit/aefd88e1ac7bed5b8c0e9dd1d9d012ceae88128b

**Comment by Fedik** [comment]
The code is was this: https://github.com/joomla-projects/joomla-a11y-checker/blob/d7567f8343d3fca5e0756fc03dd1e797c8948b64/src/js/sa11y.js#L392-L406

I commented it out. Because it looks very hacky and may be bad for initial rendering. 
Currently there no initial scanning, it happen only after user click the button.

**Comment by Fedik** [comment]
hmhm, maybe we need some method to run initialScan, that we run on load.
Kind of:
```javascript
// Instantiate
const checker = new Sa11y.Sa11y(Sa11yLangEn.options);

window.addEventListener('load', () => {
  checker.runInitialCheck();
});
```

btw, I did not seen there any animation, also on their original demo :)

**Comment by brianteeman** [comment]
The animation is a rotating border - not that important

but starting the script on load is essential

**Comment by brianteeman** [comment]
![test](https://user-images.githubusercontent.com/1296369/142918120-02642d62-5f61-48fd-b429-9a6ad4dee447.gif)
