### ISSUE TITLE
Overlapping buttons (enhancement)

### ISSUE THREAD

**Issue by adamchaboryk** [joomla-projects/joomla-a11y-checker#60]
In an attempt to fix one issue, i think i have a solution for another. I created a mini function to "nudge" buttons so they don't overlap. E.g. when a video iframe has a warning to add closed captions AND an error button stating iframe is missing title. 

````javascript
this.nudge = () => {
			const sa11yInstance = document.querySelectorAll('.sa11y-instance, .sa11y-instance-inline');
			sa11yInstance.forEach(($el) => {
				const sibling = $el.nextElementSibling;
				if (sibling !== null && (sibling.classList.contains("sa11y-instance") ||
				sibling.classList.contains("sa11y-instance-inline"))) {
					sibling.querySelector("button").setAttribute("style", "margin: -10px -20px !important;");
				}
			});
		}
````

I call this function towards the end of `this.checkAll = async () => {`

**Comment by brianteeman** [comment]
Kind of suprised that tippy (or is it popper) doesnt have something built in for this

**Comment by brianteeman** [comment]
This will be in the next merge thanks
