### ISSUE TITLE
[4.1]Some accessibility issues

### ISSUE THREAD

**Issue by niharikamahajan02** [joomla-projects/joomla-a11y-checker#70]
1) On pressing Alt+9, when keyboard navigation appears , it is not being getting accessed though tab button. We need to press downward, upward key for that matter.
![image](https://user-images.githubusercontent.com/72392580/154972710-c589098a-ded6-422c-995d-aa31671935f9.png)

2) In high contrast , when we navigate through tab button , it is not possible to see when the navigation goes from new button to options and then help.
![image](https://user-images.githubusercontent.com/72392580/154972954-bff82c38-9614-48cc-b640-5500d92e2d8f.png)

**Comment by brianteeman** [comment]
This is not the correct place to report either of these issues.
