### ISSUE TITLE
Using Jooa11y on a custom template

### ISSUE THREAD

**Issue by jjnxpct** [joomla-projects/joomla-a11y-checker#71]
Hi! I noticed the new Jooa11y feature in Joomla 4 and wanted to check it out. I think it's a great tool. Thaks for that.

When I turn the check on for all pages and go to the frontend I do see the button in the right bottom corner. But nothing happens (visually) when I click on it. I do see content in the source code but I think I might be missing some css (or js) files...

When I switch to the default J4 template everyting works as expected so this is an issue with my own template.

What css an js files need to be loaded to make this plugin work? And should all these files be loaded in my template by the plugin?

Maybe I need to add something to my custom template to make it work?

Any help is appreciated! Thanks.

**Comment by brianteeman** [comment]
It should just work so I suspect some javascript conflict. Is there any errors in the console? Or can you share the url and I can check

**Comment by jjnxpct** [comment]
@brianteeman : Thanks Brian. There are no console warnings. The URL: https://nieuw.zzuit.nl/

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/156345746-61bb1f6f-9e18-4484-b88e-faf2ddb248bc.png)

**Comment by jjnxpct** [comment]
Mmm I think my inscpector is set up wrong ;-) I'll have to look at that.

**Comment by brianteeman** [comment]
In  your template if you change `<div id=main >` to `<main>` it will work. It will also be more semantically correct

**Comment by jjnxpct** [comment]
Yep, that's it! Thanks @brianteeman !

**Comment by brianteeman** [comment]
There should have been another way in the options of the plugin but it looks like there is a bug there. So thanks for reporting this

**Comment by brianteeman** [comment]
I have fixed the issue preventing the options from working - thanks for reporting it.

https://github.com/joomla/joomla-cms/pull/37196
