### ISSUE TITLE
new release upstream

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-a11y-checker#72]
2.1 has been released upstream.

https://github.com/ryersondmp/sa11y/releases/tag/2.1.0

Just need a double check for new features

**Comment by brianteeman** [comment]
- [x] Updated interface to better support languages with multiple plurals.
- [x] New warning ruleset for <u>underlined<u> text.
- [ ] New warning ruleset for decorative images within a <figure> element.
- [x] New warning ruleset for figure elements that have duplicate alt and caption text.
- [ ] New generic warning for any type of iFrame.
- [ ] New error ruleset for finding duplicate ids.
- [x] Readability module now supports German, Dutch, and Italian.
- [x] Some tooltips have been simplified for easier translation and better readability.
- [x] Press Option + A on MacOS or Alt + A on Windows to toggle Sa11y on or off.
- [x] Additional skip-to-issue shortcut. Press Option + S on MacOS or Alt + S on Windows.
- [x] Overlapping error or warning buttons will automatically reposition.
- [ ] New modular design and introduction of JSON-like properties. Over a dozen props to customize the experience.
- [ ] Use props to add exclusions and specify target area to scan.
- [ ] Props to turn off specific plugins.
- [ ] Props to turn off individual rulesets from QA module.
- [ ] Special prop to change non-consecutive heading error to a warning (alignment with WCAG).
- [x] Removal of jQuery dependency.
- [x] Added some basic error handling when the target area element is missing on the page.
- [ ] Simplified way of adding new sources for video and audio content to flag.
- [ ] Bug fix: Alternative text ruleset now ignores <noscript> tags.

Updated from 2.1.2

- [ ] Improved accessible name computation for link text module. More accurate computation when nodes have child elements (such as <span> or <svg>.
- [ ] Both link text modules refactored based on improved accessibleName computation.
- [ ] New feature: Re-scan page if URL change detected. Support for SPAs.
- [ ] 3 new props: flagLongHeadings, showGoodLinkButton, detectSPArouting
- [ ] Moved fnIgnore to utilities.
- [ ] Cleaned up and simplified CSS reset within clearEverything function
- [ ] Added .fr, .pe, .nz, .pt, .es, .pl, .ua to link stop word check.
- [ ] Fake heading ruleset will not flag bolded text that ends with an asterisk.

**Comment by adamchaboryk** [comment]
Hey @brianteeman, just a heads up - I will be releasing another important update shortly. I'm in the process of improving the accessible name computation `this.computeAriaLabel()` for the link check modules.

**Comment by brianteeman** [comment]
Thanks for the heads up. Havent really had the time to get my head into this yet.

**Comment by adamchaboryk** [comment]
https://github.com/ryersondmp/sa11y/releases/tag/2.1.3

Edit: Please see 2.1.3 instead @brianteeman
