### ISSUE TITLE
kill the fork

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-a11y-checker#75]
The reasons that we did the hard fork were 
- Language support
- jQuery
- timescale

Upstream has now converted to vanilla - mainly as a result of the code from here
Upstream has added new tests from here
Upstream has added many new tests, features etc etc

I am thinking that we should drop the hard fork that we currently have and have a softer fork **just** for the changes we need for the language string structure.

This will make it much much easier to take new features and bug fixes from upstream than it is today. See #72 for a big thing of things to check and or add

@bembelimen @HLeithner @fedik @chmst 
Your thought and opinions really welcome. Otherwise its going to be a lot of work to keep updating our fork with the changes that @adamchaboryk is making upstream.

From a joomla core backwards compatibility stance it is not an issue.

**Comment by adamchaboryk** [comment]
Hi @brianteeman, I apologize - my updates on Sa11y are often sporadic and unplanned. Because of that, I don't expect full feature parity between our forks. Is there anything I can do to help make updates for you easier?

**Comment by bembelimen** [comment]
I can agree on it when the original is installable via NPM + @brianteeman (if you want) get at least the maintainer role like he has here. So we don't die on the way without any possibility for us to act. So not kill the fork here but merge together and collaborate?

**Comment by brianteeman** [comment]
I think I didnt really explain myself very well (as usual)

What I am proposing is that we release jooa11y 2 based on sa11y 2. With the only changes to sa11y being the changes needed to support our language file structure.

This will get our codebase back in sync with sa11y and allow us to much more easily than now apply upstream changes. jooa11y would continue as an npm package so as far as core joomla is concerned its just a library update.

It will be much faster for me to do that than to integrate all the changes in sally2 into the current jooa11y.

Moving forward with @adamchaboryk its actually easier to work with your code now that you are doing more issue specific commits as I can read the changes easier.

**Comment by HLeithner** [comment]
2 things, you can actually do the down merge without killing the fork but not with github gui (at least I didn't found a way) so you have to do it locally (add adamchaboryk repository as remote to your local repository) and push the changes into this repo.

Alternative is to fork it as Sa11y to joomla-projects and continue work on it. Other alternative is to rename this repo and and create a new fork thru github to joomla-projects/sa11y

Main question is do we need our own fork or is it enough to have some sa11y specific code in the cms it self.

It's you choice do what ever fits your needs.

**Comment by brianteeman** [comment]
> 2 things, you can actually do the down merge without killing the fork but not with github gui (at least I didn't found a way) so you have to do it locally (add adamchaboryk repository as remote to your local repository) and push the changes into this repo.

Yes I know how to do it (and  you can do it with github beta as well)  but ur repo are currently completely different and what I am proposing is to make a big change here now so that we can do that in the future.

> Main question is do we need our own fork or is it enough to have some sa11y specific code in the cms it self.

Yes fwe need a fork for the language specific stuff afaict.

> It's you choice do what ever fits your needs.

I will take a look over the weekend and make a decision etc.

Thanks all for the feedback - much appreciated!!
