### ISSUE TITLE
Form labels module: Incorrect logic for matching for and id attribute.

### ISSUE THREAD

**Issue by adamchaboryk** [joomla-projects/joomla-a11y-checker#76]
Hi,

I just noticed a flaw with my form labels logic. I think it may have gotten lost in translation from jquery to vanilla JS. This in regards to [lines 1995 to 2008](https://github.com/joomla-projects/joomla-a11y-checker/blob/joomla/src/js/jooa11y.js#L1995-L2008) of the form labels module.

```html
<label for="foo">Search</label>
<div><input id="foo"/></div>
```
The above will get flagged as an error based on the current logic. But it should not. 

To fix, `$labels` should query the entire page for "label" element, not just the previous or next element. I'll be pushing this change to my fork shortly.

```javascript
const $labels = this.root.querySelectorAll("label");
	let hasFor = false;
        $labels.forEach(($l) => {
		if (hasFor) return;
		if ($l.getAttribute('for') === el.getAttribute('id')) {
			hasFor = true;
		}
	});
````

**Comment by brianteeman** [comment]
thanks @adamchaboryk 

still trying to find some free time to move forward with jooa11y
