### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/joomla-a11y-checker#8]
There is a named argument _sa11yNewTab_ that is used in many places. However I didnt define it in our fork and every time I have tried it fails. Help appreciated.

Note that once its working I will need to review the strings to make sure its in use everywhere and in the correct places.

`const sa11yNewTab = '<span class=\'sa11y-visually-hidden\'>(Opens in new tab)</span>';`

**Comment by carcam** [comment]
Sorry to be the noob here, but I cannot find the say11NewTab anywhere in the sally.js file. What am I missing?

**Comment by brianteeman** [comment]
that's because 
>  I didnt define it in our fork 

It is used here for example

https://github.com/joomla-projects/joomla-a11y-checker/blob/238012917d93fd878d53eb62201a4009ab27e2cd/src/js/lang/en.js#L65

**Comment by carcam** [comment]
Thanks!! I will investigate from that.

Best!!

**Comment by brianteeman** [comment]
I have removed the code from the language strings. At a later date we can revisit how the links are indicated and come up with a better solution than this one for all links. Perhaps https://codersblock.com/blog/external-links-new-tabs-and-accessibility/#making-things-less-tedious
